config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :systems, except: :delete do
    post '/reset_token', on: :collection, action: 'reset_token'
  end
  namespace :access_tokens do
    get '/edit', action: 'edit'
    post '/', action: 'update'
  end
  resources :subscriptions, only: [:index, :create, :new, :destroy]
  resources :export_csvs, only: :create

  get 'dashboard/index'

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:edit, :update, :show]

  namespace :entities do
    get ':entity_class_name' => 'entities#index'
    get ':entity_class_name/show/:id' => 'entities#show', as: :show
  end

  resources :entity_types do
    post '/:id', on: :collection, action: 'update'
    member do
      get :measurement_types
    end
  end

  resources :relationship_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  resources :measurement_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  root 'dashboard#index'

  def user_constraint(request, attribute)
    user_guid = request.session['cas'].try(:[], 'extra_attributes').try(:[], 'theKeyGuid')
    User.find_by(guid: user_guid).send(attribute) if user_guid.present?
  end

  constraints -> (request) { user_constraint(request, :developer) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/entities/entities_controller.rb
module Entities
  ## EntitiesController
  class EntitiesController < BaseController
    before_action :load_entity_class

    def index
      @per = 25
      @page = params[:page].try(:to_i).presence || 1
      @entities = @entity_class.search page: @page,
                                       per_page: @per,
                                       filters: params[:filters]
    end

    def show
      @entity = @entity_class.find(params[:id])
    end

    private

    def load_entity_class
      @entity_class = "GlobalRegistryModels::Entity::#{params[:entity_class_name].classify}".safe_constantize
      redirect_to root_path if @entity_class.blank?
    end
  end
end

app/helpers/entities_helper.rb
## Entities Helpers
module EntitiesHelper
  def filters_text_field_tag(name:, label:)
    safe_join [
      label_tag("filters[#{name}]", label, class: 'control-label col-sm-4 text-right'),
      content_tag(:div, text_field_tag("filters[#{name}]", params[:filters].try(:[], name),
                                       placeholder: label, class: 'form-control'), class: 'col-sm-8')
    ]
  end
end

app/views/entities/entities/_request_csv_export_modal.slim
#requestCsvExportModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss='modal' = fa_icon 'times'
        h4.modal-title Request CSV
      = form_tag export_csvs_path(filters: params[:filters]), class: 'form-horizontal' do
        = hidden_field_tag :entity_class_name, entity_class_name
        .modal-body
          - if filters.blank?
            = alert_box context: :danger do
              strong = fa_icon 'exclamation-triangle', text: 'Warning'
              br
              'You are about to export all results without filters. If there are a lot of results then this could take an extremely long time. Please add some filters to limit your result set.
          .form-group
            = label_tag :email, 'Email', class: 'col-md-2 control-label'
            .col-md-10
              = text_field_tag :email, email, class: 'form-control', placeholder: 'Email'
              span.help-block You may request a CSV export of the #{ entity_class_name.to_s.titleize } results seen on this page. The CSV export will be emailed to this address when it's ready.
        .modal-footer
          .btn-group
            button.btn.btn-default data-dismiss='modal' Cancel
            = submit_tag 'Request CSV', class: 'btn btn-primary', data: { disable: '...' }

app/views/entities/entities/index.slim
h1 = @entity_class.title.pluralize

.form-group.btn-group
  = link_to fa_icon('file-text', text: 'Request CSV'), '#', class: 'btn btn-default', data: { toggle: 'modal', target: '#requestCsvExportModal' }

.row

  .col-md-8
    .table-responsive
      table.table.table-striped.table-hover.table-condensed
        thead
          tr
            - @entity_class.identifying_attributes.each do |attribute|
              th = titleize_attribute attribute
            th
        tbody
          - @entities.each do |entity|
            tr
              - @entity_class.identifying_attributes.each do |attribute|
                td = truncate entity.send(attribute)
              td = link_to fa_icon(:eye, text: 'Details'), entities_show_path(entity_class_name: @entity_class.name.pluralize, id: entity.id), class: 'btn btn-link btn-xs'

    .form-group = paginate_collection @entities

  .col-md-4
    .panel.panel-default
      .panel-heading: h3.panel-title = fa_icon 'filter', text: 'Filters'
      .panel-body
        = form_tag entities_path, class: 'form-horizontal', method: :get do
          - @entity_class.filterable_attributes.each do |attribute|
            .form-group.form-group-sm = filters_text_field_tag(name: "#{attribute.to_s}:like", label: titleize_attribute(attribute))
          .btn-group
            = button_tag fa_icon('filter', text: 'Filter'), method: 'get', class: 'btn btn-primary', data: { disable_with: '...' }
            = link_to fa_icon('undo', text: 'Reset'), entities_path(entity_class_name: @entity_class.name.pluralize), class: 'btn btn-default', data: { disable_with: '...' }

= render 'request_csv_export_modal', entity_class_name: @entity_class.name, filters: params[:filters], email: current_user.email