config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :systems, except: :delete do
    post '/reset_token', on: :collection, action: 'reset_token'
  end
  namespace :access_tokens do
    get '/edit', action: 'edit'
    post '/', action: 'update'
  end
  resources :subscriptions, only: [:index, :create, :new, :destroy]
  resources :export_csvs, only: :create

  get 'dashboard/index'

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:edit, :update, :show]

  namespace :entities do
    get ':entity_class_name' => 'entities#index'
    get ':entity_class_name/show/:id' => 'entities#show', as: :show
  end

  resources :entity_types do
    post '/:id', on: :collection, action: 'update'
    member do
      get :measurement_types
    end
  end

  resources :relationship_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  resources :measurement_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  root 'dashboard#index'

  def user_constraint(request, attribute)
    user_guid = request.session['cas'].try(:[], 'extra_attributes').try(:[], 'theKeyGuid')
    User.find_by(guid: user_guid).send(attribute) if user_guid.present?
  end

  constraints -> (request) { user_constraint(request, :developer) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/subscriptions_controller.rb
## Subscriptions Controller
class SubscriptionsController < BaseController
  before_action :check_for_token
  before_action :fetch_entity_types, only: [:index, :new]

  def index
    @subscriptions = GlobalRegistryModels::Subscription::Subscription.search
  end

  def new
  end

  def create
    begin
      GlobalRegistryModels::Subscription::Subscription
        .create(subscription_params)
    rescue RestClient::BadRequest
      flash[:error] = 'An error has occured'
    else
      flash[:success] = 'Subscription was successfully added.'
    end
    redirect_to subscriptions_url
  end

  def destroy
    GlobalRegistryModels::Subscription::Subscription.delete params[:id]
    flash[:success] = 'Subscription was successfully removed.'
    redirect_to subscriptions_url
  end

  private

  def fetch_entity_types
    @entity_types =
      GlobalRegistryModels::EntityType::EntityType
      .search(page: 1, per_page: 100)
      .order(:name)
  end

  def subscription_params
    params.require(:subscription).permit(:entity_type_id,
                                         :endpoint, :client_integration_id)
  end
end

app/helpers/subscriptions_helper.rb
## Subscriptions Helper
module SubscriptionsHelper
  def entity_type_name(entity_type_id)
    @entity_types.find { |entity_type| entity_type.id == entity_type_id }.try(:name)
  end
end

app/views/subscriptions/_form.html.erb
<%= form_for('subscription', url: '/subscriptions', html: {class: "col-sm-6 col-sm-offset-3"}) do |f| %>

  <div class="form-group">
    <%= f.collection_select(:entity_type_id, 
      @entity_types, :id, :name,
      {:prompt => 'Please select an entity type'}, class: "form-control", :required => true)  %>
  </div>

  <div class="form-group">
    <%= f.text_field :endpoint, class: "form-control", placeholder: "The url endpoint starting with http://..", :required => true  %>
  </div>

  <div class="form-group">
    <%= f.submit "Subscribe", class:"form-control btn btn-primary" %>
  </div>
  
  <div class="form-group">
    <%= link_to 'Back', subscriptions_path, class:"btn btn-info form-control" %>
  </div>

<% end %>

app/views/subscriptions/index.html.erb
<h1> Listing subscriptions </h1>
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th> Entity type </th>
      <th> Endpoint </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= entity_type_name(subscription.entity_type_id) %></td>
        <td><%= subscription.endpoint %></td>
        <td><%= link_to 'Unsubscribe', "subscriptions/#{subscription.id}", data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Subscription', new_subscription_path, class:"btn btn-info" %>

app/views/subscriptions/new.html.erb
<h1 class="text-center"> New subscription </h1>
<div class="row">
  <%= render 'form' %>
</div>