config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :systems, except: :delete do
    post '/reset_token', on: :collection, action: 'reset_token'
  end
  namespace :access_tokens do
    get '/edit', action: 'edit'
    post '/', action: 'update'
  end
  resources :subscriptions, only: [:index, :create, :new, :destroy]
  resources :export_csvs, only: :create

  get 'dashboard/index'

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:edit, :update, :show]

  namespace :entities do
    get ':entity_class_name' => 'entities#index'
    get ':entity_class_name/show/:id' => 'entities#show', as: :show
  end

  resources :entity_types do
    post '/:id', on: :collection, action: 'update'
    member do
      get :measurement_types
    end
  end

  resources :relationship_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  resources :measurement_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  root 'dashboard#index'

  def user_constraint(request, attribute)
    user_guid = request.session['cas'].try(:[], 'extra_attributes').try(:[], 'theKeyGuid')
    User.find_by(guid: user_guid).send(attribute) if user_guid.present?
  end

  constraints -> (request) { user_constraint(request, :developer) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/systems_controller.rb
## Systems Controller
class SystemsController < BaseController
  before_action :check_for_token
  before_action :set_system, only: [:show, :edit]
  before_action :set_system_of_user, only: [:index, :show, :new, :edit]
  before_action :update_params, only: [:update, :create]

  def index
    @per_page = 80
    @page = params[:page] ||= 1
    @systems = GlobalRegistryModels::System::System.search(page: @page.to_i, per_page: @per_page).order(:name)
  end

  def show
  end

  def new
    @url = '/systems'
  end

  def edit
    @url = "/systems/#{@system.id}"
    @method = :patch
  end

  def create
    save_system
  end

  def update
    save_system
  end

  def reset_token
    system = GlobalRegistryModels::System::System.new id: params[:reset_token][:system_id]
    begin
      updated_system = system.reset_access_token
    rescue RestClient::BadRequest
      flash[:error] = 'An error has occured.'
    else
      flash[:success] =
        "The access token has been resetted to #{updated_system.access_token}."
    end
    redirect_to edit_system_path(params[:reset_token][:system_id])
  end

  private

  def save_system
    try_saving
    redirect_to systems_url
  end

  def try_saving
    system_class.update(params[:id], systems_params) if params[:id]
    system_class.create(systems_params) unless params[:id]
  rescue RestClient::BadRequest, RuntimeError
    flash[:error] = 'An error has occured'
  else
    flash[:success] = 'The system was successfully updated.'
  end

  def system_class
    GlobalRegistryModels::System::System
  end

  def update_params
    if params[:system][:trusted_ips]
      params[:system][:trusted_ips] = params[:system][:trusted_ips].split(', ')
    end
  end

  def set_system
    @system = GlobalRegistryModels::System::System.find params[:id]
  end

  def systems_params
    params.require(:system)
          .permit(:name, :contact_name, :contact_email,
                  :permalink, :root, trusted_ips: [])
  end
end

app/helpers/systems_helper.rb
## Systems Helper
module SystemsHelper
  def system_class
    GlobalRegistryModels::System::System
  end

  def formatted_value(attribute)
    f_value = @system.send attribute
    f_value = f_value.join(', ') if f_value.is_a?(Array)
    f_value
  end

  def relevant_attributes
    relevant_attributes = system_class.identifying_attributes unless root_user?
    relevant_attributes = system_class.identifying_root_attributes if root_user?
    relevant_attributes
  end

  def root_user?
    @system_of_user.root
  end

  def system_owner?
    @system_of_user == @system
  end

  def can_edit?(system)
    root_user? || @system_of_user.id == system.id
  end
end

app/views/systems/_form.html.erb
<div class="row">
  <div class = "col-sm-6 col-sm-offset-3">
    <%= form_for('system', url: @url, method: @method ) do |f| %>
      <% relevant_attributes.each do |attribute| %>
        <%= form_attribute_to_field('system', attribute, @system)%>  
      <% end %>
      <div class="form-group"><%=f.submit 'Save', class:'btn btn-primary form-control' %></div>
    <% end %>
    <%= render 'reset_token_form' %>
    <div class="form-group"><%= link_to 'Back', systems_path, class: "btn btn-info form-control" %></div>
  </div>
</div>

app/views/systems/_reset_token_form.html.erb
<% if action_name == 'edit' %>
  <hr>
  <%= form_for 'reset_token', url: '/systems/reset_token' do |f| %>
    <%= f.hidden_field :system_id, value: @system.id %>
    <div class="form-group">
      <%= f.submit "Reset Access Token", class: "btn btn-warning form-control" %>
    </div>
  <% end %>
  <hr>
<% end %>

app/views/systems/edit.html.erb
<h1 class="text-center">Editing System</h1>

<%= render 'form' %>

app/views/systems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Systems</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact name</th>
      <th>Contact email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @systems[0...-1].each do |system| %>
      <tr>
        <td><%= link_to system.name, system_path(system.id) %></td>
        <td><%= system.contact_name %></td>
        <td><%= system.contact_email %></td>
        <td><%= if can_edit?(system) then link_to('Edit', edit_system_path(system.id)) end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-group"><%= paginate_collection @systems %></div>

<br>
<% if root_user? %>
  <%= link_to 'New System', new_system_path, class: "btn btn-info" %>
<% end %>

app/views/systems/new.html.erb
<h1 class="text-center">New System</h1>

<%= render 'form' %>

app/views/systems/show.html.erb
<div class="row">
  <div class="panel panel-default col-sm-6 col-sm-offset-3">
    <div class="panel-body">
      <h3>System Details</h3>
      <% relevant_attributes.each_with_index do |attribute, i| %>
          <b><%= attribute.to_s %></b>
          <p><%= formatted_value(attribute) %></p>
      <% end %>
    </div>
    <% if can_edit?(@system) %>
      <%= link_to 'Edit', edit_system_path(@system.id), class: "btn btn-success form-control" %>
    <% end %>
    <%= link_to 'Back', systems_path, class: "btn btn-info form-control" %>
  </div>
</div>