config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :systems, except: :delete do
    post '/reset_token', on: :collection, action: 'reset_token'
  end
  namespace :access_tokens do
    get '/edit', action: 'edit'
    post '/', action: 'update'
  end
  resources :subscriptions, only: [:index, :create, :new, :destroy]
  resources :export_csvs, only: :create

  get 'dashboard/index'

  resource :session, only: [:new, :create, :destroy]

  resources :users, except: [:edit, :update, :show]

  namespace :entities do
    get ':entity_class_name' => 'entities#index'
    get ':entity_class_name/show/:id' => 'entities#show', as: :show
  end

  resources :entity_types do
    post '/:id', on: :collection, action: 'update'
    member do
      get :measurement_types
    end
  end

  resources :relationship_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  resources :measurement_types, only: :create do
    post '/:id', on: :collection, action: 'update'
  end

  root 'dashboard#index'

  def user_constraint(request, attribute)
    user_guid = request.session['cas'].try(:[], 'extra_attributes').try(:[], 'theKeyGuid')
    User.find_by(guid: user_guid).send(attribute) if user_guid.present?
  end

  constraints -> (request) { user_constraint(request, :developer) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_navbar.slim
= navbar inverted: true, position: :top do
  = vertical do
    = link_to 'Nebo', root_path
  = horizontal do
    - if signed_in?
      = nav class: 'navbar-left' do
        = link_to fa_icon('dashboard', text: 'Dashboard'), root_path
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            = fa_icon 'binoculars', text: 'Entities'
            span.caret
          ul.dropdown-menu
            - entities.each do |entity_class|
              li = link_to entity_class.title.pluralize, entities_path(entity_class_name: entity_class.name.pluralize)
            hr
            li = link_to 'Entity Types', entity_types_path
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            = fa_icon 'gear', text: 'Admin'
            span.caret
          ul.dropdown-menu
            li = link_to fa_icon('users', text: 'Users'), users_path
        - if own_token?
          li = link_to 'Subscriptions', subscriptions_path
          li = link_to 'Systems', systems_path
        li = link_to 'Access Token', access_tokens_edit_path

      = nav class: 'navbar-right' do
        = link_to fa_icon(:key, text: current_user), 'https://thekey.me/cas/service/selfservice?target=displayAccountDetails', target: '_blank'
        = link_to fa_icon('sign-out', text: 'Sign Out'), session_path, method: :delete

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    /! The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    link href="../../favicon.ico" rel="icon" /

    title Nebo

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render 'layouts/navbar'
    .container
      - flash.each do |type, message|
        = alert_box message, context: flash_type_to_bootstrap_class(type), dismissible: true
      = yield
    footer.footer: .container: .row: .col-md-12.text-center.text-muted
      = ['Nebo', '© 2015 Cru.'].join ' · '